[build]
  publish = "."

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=300"
    Access-Control-Allow-Origin = "*"
    Content-Type = "application/javascript; charset=utf-8"
